import Link from "next/link";
import { panelClass } from "@/modules/clients/presentation";
import { formatIsraeliDate, formatIsraeliShekels } from "@/modules/dashboard/format";
import { getSafeHttpsUrl } from "@/modules/documents/validation";
import { AccountingObligationCheck, AccountingObligationForm, type AccountingOptions, ExpenseForm, LiabilityForm, ManualIncomeForm, TaxPaymentForm, TrustTransactionForm } from "./forms";
import type { getAccountingOverview } from "./queries";

type Overview = Awaited<ReturnType<typeof getAccountingOverview>>;
function Card({ label, amount, emphasized = false }: { label: string; amount: string; emphasized?: boolean }) { return <div className={emphasized ? "rounded-lg bg-teal-50 p-3" : "rounded-lg border border-stone-100 p-3"}><dt className="text-sm text-stone-600">{label}</dt><dd className="mt-1 text-xl font-bold" dir="ltr">{formatIsraeliShekels(amount)}</dd></div>; }
function linkForMonth(key: string, shift: number) { const [year, month] = key.split("-").map(Number); const value = new Date(Date.UTC(year, month - 1 + shift, 1)); return `${value.getUTCFullYear()}-${String(value.getUTCMonth() + 1).padStart(2, "0")}`; }
function DetailList({ children }: { children: React.ReactNode }) { return <ul className="mt-3 divide-y divide-stone-100">{children}</ul>; }

export function AccountingPageContent({ data, options, today }: { data: Overview; options: AccountingOptions; today: string }) {
  const { summary, month } = data;
  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">הנהלת חשבונות</h1><p className="mt-1 text-sm text-stone-600">תצוגת בקרה חודשית; אינה מערכת הנהלת חשבונות פורמלית.</p></div>
      <details className="rounded-lg border border-stone-200 bg-white p-3"><summary className="cursor-pointer font-medium text-teal-800">+ הוסף</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">
        <details><summary className="cursor-pointer underline">הכנסה אחרת</summary><ManualIncomeForm today={today} /></details><details><summary className="cursor-pointer underline">הוצאה</summary><ExpenseForm today={today} /></details><details><summary className="cursor-pointer underline">כספי נאמנות</summary><TrustTransactionForm today={today} options={options} /></details><details><summary className="cursor-pointer underline">תשלום מס</summary><TaxPaymentForm today={today} options={options} /></details><details><summary className="cursor-pointer underline">תשלום מע״מ</summary><TaxPaymentForm today={today} options={options} vat /></details><details><summary className="cursor-pointer underline">סכום לתשלום</summary><LiabilityForm /></details><details><summary className="cursor-pointer underline">התחייבות הנה״ח</summary><AccountingObligationForm /></details>
      </div></details></header>
    <nav className="flex items-center justify-center gap-5" aria-label="בחירת חודש"><Link className="text-teal-700 underline" href={`/accounting?month=${linkForMonth(month.key, -1)}`}>→ חודש קודם</Link><h2 className="font-semibold capitalize">{month.label}</h2><Link className="text-teal-700 underline" href={`/accounting?month=${linkForMonth(month.key, 1)}`}>חודש הבא ←</Link></nav>
    <section className={`${panelClass} grid gap-3 sm:grid-cols-3`}><Card label="הכנסות" amount={summary.totalIncome} emphasized /><Card label="הוצאות" amount={summary.expenseTotal} /><Card label="נטו תפעולי לפני מס ומע״מ" amount={summary.operatingNet} /></section>
    <section className={`${panelClass} grid gap-3 sm:grid-cols-3`}><Card label="מס ששולם" amount={summary.taxPaid} /><Card label="מע״מ ששולם" amount={summary.vatPaid} /><Card label="נטו לאחר תשלומי מס ומע״מ" amount={summary.cashNet} /></section>
    <section className={`${panelClass} grid gap-3 sm:grid-cols-2 lg:grid-cols-4`}><Card label="חוב מס" amount={summary.openTaxOwed} /><Card label="חוב מע״מ" amount={summary.openVatOwed} /><Card label="לקוחות חייבים" amount={summary.receivablesTotal} /><Card label="כספי נאמנות" amount={summary.trustBalance} /></section>
    <section className={panelClass}><h2 className="text-lg font-bold">התחייבויות הנהלת חשבונות</h2>{data.obligations.length ? <DetailList>{data.obligations.map((row) => <li key={row.id} className="py-3"><AccountingObligationCheck id={row.id} done={row.done} title={row.title} />{(row.dueDate || row.type || row.amount) && <p className="mt-1 text-sm text-stone-500">{[row.dueDate && `עד ${formatIsraeliDate(row.dueDate)}`, row.type, row.amount && formatIsraeliShekels(row.amount)].filter(Boolean).join(" · ")}</p>}{row.description && <p className="mt-1 text-sm text-stone-600">{row.description}</p>}</li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין התחייבויות הנהלת חשבונות.</p>}</section>
    <section className={panelClass}><h2 className="text-lg font-bold">הכנסות — {month.label}</h2><DetailList>{data.clientPayments.map((row) => <li key={`client-${row.id}`} className="py-3"><p><Link className="font-medium text-teal-800 underline" href={`/clients/${row.clientId}`}>{row.clientName}</Link> <span className="text-sm text-stone-500">תשלום לקוח · {formatIsraeliDate(row.recordDate)}</span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi></p>{row.matterTitle && <p className="mt-1 text-sm text-stone-500">{row.matterTitle}</p>}</li>)}{data.incomeRows.map((row) => <li key={`income-${row.id}`} className="py-3"><span>הכנסה אחרת · {row.description}</span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi></li>)}</DetailList><p className="mt-3 border-t pt-3 font-semibold">סה״כ הכנסות <bdi className="float-left" dir="ltr">{formatIsraeliShekels(summary.totalIncome)}</bdi></p></section>
    <section className={panelClass}><h2 className="text-lg font-bold">הוצאות</h2>{data.expenses.length ? <DetailList>{data.expenses.map((row) => <li key={row.id} className="py-3"><span>{formatIsraeliDate(row.recordDate)} · {row.description}{row.category && ` · ${row.category}`}</span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi>{row.documentLink && getSafeHttpsUrl(row.documentLink) && <a className="mt-1 block text-sm text-teal-700 underline" href={getSafeHttpsUrl(row.documentLink)!} target="_blank" rel="noreferrer">פתח מסמך</a>}</li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין הוצאות בחודש זה.</p>}</section>
    <section className={panelClass}><h2 className="text-lg font-bold">תשלומים</h2>{data.outgoingPayments.length ? <DetailList>{data.outgoingPayments.map((row) => <li key={row.id} className="py-3"><span>{formatIsraeliDate(row.recordDate)} · {row.description} <span className="text-sm text-stone-500">{row.kind}</span></span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi></li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין תשלומים בחודש זה.</p>}</section>
    <section className={panelClass}><h2 className="text-lg font-bold">כספי נאמנות</h2>{data.trustRows.length ? <DetailList>{data.trustRows.map((row) => <li key={row.id} className="py-3"><Link className="font-medium text-teal-800 underline" href={`/clients/${row.clientId}`}>{row.clientName}</Link><span className="ms-2 text-sm text-stone-500">{row.transactionType === "receipt" ? "קבלה לנאמנות" : "שחרור נאמנות"}{row.matterTitle && ` · ${row.matterTitle}`}</span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi></li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין פעולות נאמנות בחודש זה.</p>}</section>
    <section className={panelClass}><h2 className="text-lg font-bold">מסים ומע״מ</h2>{data.liabilities.length ? <DetailList>{data.liabilities.map((row) => <li key={row.id} className="py-3"><span>{row.liabilityType === "vat" ? "מע״מ" : "מס"} · {row.status === "open" ? "פתוח" : "שולם"}{row.period && ` · ${row.period}`}</span><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.amount)}</bdi></li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין סכומים לתשלום.</p>}</section>
    <section className={panelClass}><h2 className="text-lg font-bold">לקוחות חייבים</h2>{data.receivables.length ? <DetailList>{data.receivables.map((row) => <li key={row.clientId} className="py-3"><Link className="font-medium text-teal-800 underline" href={`/clients/${row.clientId}`}>{row.clientName}</Link><bdi className="float-left font-semibold" dir="ltr">{formatIsraeliShekels(row.balance)}</bdi></li>)}</DetailList> : <p className="mt-3 text-sm text-stone-500">אין יתרות פתוחות.</p>}</section>
    {data.legacyRecords.length > 0 && <section className={panelClass}><h2 className="text-lg font-bold">רשומות קודמות</h2><p className="mt-1 text-sm text-stone-500">רשומות מהמודול הישן נשמרו ללא סיווג אוטומטי ואינן נכללות בסיכום החדש.</p><DetailList>{data.legacyRecords.map((row) => <li key={row.id} className="py-3">{row.description}<bdi className="float-left font-semibold" dir="ltr">{row.amount && formatIsraeliShekels(row.amount)}</bdi></li>)}</DetailList></section>}
  </div>;
}
