"use client";
import { useActionState, useState, useTransition } from "react";
import { buttonClass, inputClass } from "@/modules/clients/presentation";
import { addAccountingLiability, addAccountingObligation, addExpense, addManualIncome, addTaxPayment, addTrustTransaction, setAccountingObligationDone, updateAccountingLiability, updateAccountingObligation, updateExpense, updateLegacyAccountingRecord, updateManualIncome, updateTaxPayment, updateTrustTransaction, type AccountingFormState } from "./actions";
const initialState: AccountingFormState = {};
export type AccountingOptions = { clients: { id: string; name: string }[]; matters: { id: string; clientId: string; title: string }[]; openLiabilities: { id: string; liabilityType: "tax" | "vat"; amount: string; period: string | null }[] };
function Feedback({ state }: { state: AccountingFormState }) { return <div aria-live="polite">{state.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>}{state.success && <p className="text-sm text-teal-800">{state.success}</p>}</div>; }
function Submit({ pending, label = "שמור" }: { pending: boolean; label?: string }) { return <button className={buttonClass} disabled={pending}>{pending ? "שומר…" : label}</button>; }
function AmountDate({ today, initialDate, initialAmount }: { today: string; initialDate?: string; initialAmount?: string }) { return <><label>תאריך (חובה)<input className={inputClass} type="date" name="recordDate" dir="ltr" defaultValue={initialDate ?? today} required /></label><label>סכום (₪) (חובה)<input className={inputClass} name="amount" inputMode="decimal" dir="ltr" required maxLength={15} defaultValue={initialAmount ?? ""} /></label></>; }
export function ManualIncomeForm({ today, recordId, initial }: { today: string; recordId?: string; initial?: { recordDate: string; description: string; amount: string; notes: string | null } }) {
  const save = recordId ? updateManualIncome.bind(null, recordId) : addManualIncome;
  const [state, action, pending] = useActionState(save, initialState);
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><AmountDate today={today} initialDate={v("recordDate")} initialAmount={v("amount")} /><label className="sm:col-span-2">תיאור (חובה)<textarea className={inputClass} name="description" required rows={2} defaultValue={v("description")} /></label><label className="sm:col-span-2">הערות<textarea className={inputClass} name="notes" rows={2} defaultValue={v("notes")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן הכנסה" : "שמור"} /></form>;
}
export function ExpenseForm({ today, recordId, initial }: { today: string; recordId?: string; initial?: { recordDate: string; description: string; amount: string; category: string | null; documentLink: string | null; notes: string | null } }) {
  const save = recordId ? updateExpense.bind(null, recordId) : addExpense;
  const [state, action, pending] = useActionState(save, initialState);
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><AmountDate today={today} initialDate={v("recordDate")} initialAmount={v("amount")} /><label className="sm:col-span-2">תיאור (חובה)<textarea className={inputClass} name="description" required rows={2} defaultValue={v("description")} /></label><label>קטגוריה<select className={inputClass} name="category" defaultValue={v("category")}><option value="">ללא קטגוריה</option><option>משרד</option><option>תוכנה</option><option>שירותים מקצועיים</option><option>הוצאות משפט</option><option>נסיעות</option><option>אחר</option></select></label><label>מסמך / קישור<input className={inputClass} name="documentLink" dir="ltr" defaultValue={v("documentLink")} /></label><label className="sm:col-span-2">הערות<textarea className={inputClass} name="notes" rows={2} defaultValue={v("notes")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן הוצאה" : "שמור"} /></form>;
}
export function TrustTransactionForm({ today, options, recordId, initial }: { today: string; options: AccountingOptions; recordId?: string; initial?: { clientId: string; matterId: string | null; transactionType: string; recordDate: string; amount: string; description: string | null; documentLink: string | null } }) {
  const save = recordId ? updateTrustTransaction.bind(null, recordId, initial?.clientId ?? "") : addTrustTransaction;
  const [state, action, pending] = useActionState(save, initialState);
  const [clientId, setClientId] = useState(state.values?.clientId ?? initial?.clientId ?? "");
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><label>לקוח (חובה)<select className={inputClass} name="clientId" required value={clientId} onChange={(e) => setClientId(e.target.value)}><option value="">בחירת לקוח</option>{options.clients.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>תיק<select className={inputClass} name="matterId" defaultValue={v("matterId")}><option value="">ללא תיק</option>{options.matters.filter((m) => !clientId || m.clientId === clientId).map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>פעולה (חובה)<select className={inputClass} name="transactionType" defaultValue={v("transactionType") || "receipt"}><option value="receipt">קבלה לנאמנות</option><option value="release">שחרור מנאמנות</option></select></label><AmountDate today={today} initialDate={v("recordDate")} initialAmount={v("amount")} /><label className="sm:col-span-2">תיאור<textarea className={inputClass} name="description" rows={2} defaultValue={v("description")} /></label><label className="sm:col-span-2">מסמך / קישור<input className={inputClass} name="documentLink" dir="ltr" defaultValue={v("documentLink")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן נאמנות" : "שמור"} /></form>;
}
export function TaxPaymentForm({ today, options, vat = false, recordId, initial }: { today: string; options: AccountingOptions; vat?: boolean; recordId?: string; initial?: { paymentKind: string; taxType: string | null; liabilityId: string | null; recordDate: string; amount: string; period: string | null; description: string | null; documentLink: string | null; notes: string | null } }) {
  const save = recordId ? updateTaxPayment.bind(null, recordId) : addTaxPayment;
  const [state, action, pending] = useActionState(save, initialState);
  const kind = initial?.paymentKind ?? (vat ? "vat" : "tax");
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><input type="hidden" name="paymentKind" value={kind} /><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><AmountDate today={today} initialDate={v("recordDate")} initialAmount={v("amount")} />{kind !== "vat" && <label>סוג מס (חובה)<select className={inputClass} name="taxType" required defaultValue={v("taxType") || "income_tax"}><option value="income_tax">מס הכנסה</option><option value="national_insurance">ביטוח לאומי</option><option value="other">אחר</option></select></label>}{recordId ? <><input type="hidden" name="liabilityId" value={v("liabilityId")} />{initial?.liabilityId && <p className="self-end text-sm text-stone-500">הקישור לסכום ששולם נשמר בעת העריכה.</p>}</> : <label>לסגירת סכום לתשלום<select className={inputClass} name="liabilityId" defaultValue={v("liabilityId")}><option value="">ללא קישור</option>{options.openLiabilities.filter((l) => l.liabilityType === kind).map((l) => <option key={l.id} value={l.id}>{l.period ?? (kind === "vat" ? `מע"מ` : "מס")} — ₪{l.amount}</option>)}</select></label>}<label>תקופה<input className={inputClass} name="period" defaultValue={v("period")} /></label><label className="sm:col-span-2">תיאור<textarea className={inputClass} name="description" rows={2} defaultValue={v("description")} /></label><label className="sm:col-span-2">מסמך / קישור<input className={inputClass} name="documentLink" dir="ltr" defaultValue={v("documentLink")} /></label><label className="sm:col-span-2">הערות<textarea className={inputClass} name="notes" rows={2} defaultValue={v("notes")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן תשלום מס" : "שמור"} /></form>;
}
export function LiabilityForm({ recordId, initial }: { recordId?: string; initial?: { liabilityType: string; amount: string; dueDate: string | null; period: string | null; description: string | null; notes: string | null } }) {
  const save = recordId ? updateAccountingLiability.bind(null, recordId) : addAccountingLiability;
  const [state, action, pending] = useActionState(save, initialState);
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><label>סוג (חובה)<select className={inputClass} name="liabilityType" defaultValue={v("liabilityType") || "tax"}><option value="tax">מס</option><option value="vat">מע״מ</option></select></label><label>סכום (₪) (חובה)<input className={inputClass} name="amount" inputMode="decimal" required dir="ltr" defaultValue={v("amount")} /></label><label>מועד לתשלום<input className={inputClass} type="date" name="dueDate" dir="ltr" defaultValue={v("dueDate")} /></label><label>תקופה<input className={inputClass} name="period" defaultValue={v("period")} /></label><label className="sm:col-span-2">תיאור<textarea className={inputClass} name="description" rows={2} defaultValue={v("description")} /></label><label className="sm:col-span-2">הערות<textarea className={inputClass} name="notes" rows={2} defaultValue={v("notes")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן סכום לתשלום" : "שמור"} /></form>;
}
export function AccountingObligationForm({ recordId, initial }: { recordId?: string; initial?: { title: string; dueDate: string | null; type: string | null; period: string | null; amount: string | null; description: string | null } }) {
  const save = recordId ? updateAccountingObligation.bind(null, recordId) : addAccountingObligation;
  const [state, action, pending] = useActionState(save, initialState);
  const v = (f: keyof NonNullable<typeof initial>) => state.values?.[f] ?? initial?.[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2">כותרת (חובה)<input className={inputClass} name="title" required defaultValue={v("title")} /></label><label>מועד<input className={inputClass} type="date" name="dueDate" dir="ltr" defaultValue={v("dueDate")} /></label><label>סוג<input className={inputClass} name="type" defaultValue={v("type")} /></label><label>תקופה<input className={inputClass} name="period" defaultValue={v("period")} /></label><label>סכום<input className={inputClass} name="amount" inputMode="decimal" dir="ltr" defaultValue={v("amount")} /></label><label className="sm:col-span-2">תיאור<textarea className={inputClass} name="description" rows={2} defaultValue={v("description")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label={recordId ? "עדכן התחייבות" : "שמור"} /></form>;
}
export function LegacyAccountingRecordForm({ recordId, initial }: { recordId: string; initial: { type: string; recordDate: string; description: string; amount: string | null; documentLink: string | null; notes: string | null } }) {
  const [state, action, pending] = useActionState(updateLegacyAccountingRecord.bind(null, recordId), initialState);
  const v = (f: keyof typeof initial) => state.values?.[f] ?? initial[f] ?? "";
  return <form action={action} className="mt-4 space-y-3" noValidate><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><label>סוג (חובה)<input className={inputClass} name="type" required maxLength={100} defaultValue={v("type")} /></label><label>תאריך (חובה)<input className={inputClass} type="date" name="recordDate" required dir="ltr" defaultValue={v("recordDate")} /></label><label className="sm:col-span-2">תיאור (חובה)<textarea className={inputClass} name="description" required rows={2} defaultValue={v("description")} /></label><label>סכום<input className={inputClass} name="amount" inputMode="decimal" dir="ltr" defaultValue={v("amount")} /></label><label>מסמך / קישור<input className={inputClass} name="documentLink" dir="ltr" defaultValue={v("documentLink")} /></label><label className="sm:col-span-2">הערות<textarea className={inputClass} name="notes" rows={2} defaultValue={v("notes")} /></label></fieldset><Feedback state={state} /><Submit pending={pending} label="עדכן רשומה קודמת" /></form>;
}
export function AccountingObligationCheck({ id, done, title }: { id: string; done: boolean; title: string }) { const [checked, setChecked] = useState(done); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string>(); return <div><label className="flex items-center gap-3"><input type="checkbox" checked={checked} disabled={pending} onChange={(event) => { const next = event.currentTarget.checked; setChecked(next); startTransition(async () => { const result = await setAccountingObligationDone(id, next); if (result.error) { setChecked(!next); setMessage(result.error); } }); }} /><span className={checked ? "text-stone-500 line-through" : "font-medium"}>{title}</span></label>{message && <p role="alert" className="mt-1 text-sm text-red-800">{message}</p>}</div>; }
